
@baseUrl = http://127.0.0.1:3000/
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxOSwiaWF0IjoxNjMzMzg0NTM3fQ.Qr6q7_D-rSZaqGCayhVPuF30MxS72fyVoUHLXCTIpoM

### Login
POST {{baseUrl}}auth/login HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "email": "armando@armando.com",
    "password": "password"
}


### I'm logged in?
GET {{baseUrl}}auth/me HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}
